# Модуль NumPy. Действия с массивами

## Изменение формы массива

In [2]:
import numpy as np

arr = np.arange(8)
print(arr)

[0 1 2 3 4 5 6 7]


In [3]:
arr.shape = (2, 4)
print(arr) 

[[0 1 2 3]
 [4 5 6 7]]


In [4]:
arr = np.arange(8)
arr_new = arr.reshape(2, 4)
print(arr)
print(arr_new)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


- Присвоение нового значения атрибуту __shape__ изменяет тот массив, с которым производится действие.
- Чтобы оставить исходный массив без изменений и дополнительно получить новый массив новой формы, нужно использовать функцию __reshape__. Она также принимает в качестве аргумента кортеж из чисел для формы, __но возвращает новый массив, а не изменяет исходный__

In [5]:
arr = np.arange(8)
arr_c = arr.reshape((2,4,), order='C') # roder = 'C' - задан по умолчанию
arr_f = arr.reshape((2,4,), order='F')
print(arr)
print(arr_c)
print(arr_f)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0 2 4 6]
 [1 3 5 7]]


In [6]:
arr = np.arange(8)
arr.shape = (2, 4)
print(arr)
print(arr.shape)
print()
arr_t = arr.transpose()
print(arr_t)
print(arr_t.shape)

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
(4, 2)


In [7]:
arr = np.arange(8)
print(arr.shape)
arr_t = arr.transpose()
print(arr_t.shape)

(8,)
(8,)


## Индексы и срезы в массивах

In [8]:
arr =np.linspace(1, 2, 6)
print(arr)

[1.  1.2 1.4 1.6 1.8 2. ]


In [9]:
print(arr[2])
print(arr[2:4])
print(arr[::-1])

1.4
[1.4 1.6]
[2.  1.8 1.6 1.4 1.2 1. ]


- многомерный массив

In [17]:
nd_arr = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
print(nd_arr)

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [57]:
print(nd_arr.transpose())

[[0.  2.  4. ]
 [0.5 2.5 4.5]
 [1.  3.  5. ]
 [1.5 3.5 5.5]]


In [18]:
print(nd_arr[1, 2])

3.0


In [23]:
print(nd_arr[:2, 2])

[1. 3.]


In [25]:
print(nd_arr[1:, 2:])

[[3.  3.5]
 [5.  5.5]]


In [38]:
print(nd_arr[2]) # берётся только 2-я по индексу строка

[4.  4.5 5.  5.5]


In [37]:
print(nd_arr[:,2]) # берётся только 2-й по индексу столбец

[1. 3. 5.]


In [39]:
print(nd_arr[:2]) # берётся срез всех строк с 0 по 1 индексу 

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]]


In [40]:
print(nd_arr[:,:2]) # берётся срез всех столбцов с 0 по 1 индексу 

[[0.  0.5]
 [2.  2.5]
 [4.  4.5]]


## Сортировка одномерных массивов

- 1-й способ. Возвращение нового сортированного масива

In [66]:
arr = np.random.randint(50, size=10)
print(arr)

arr_sort = np.sort(arr)
print(arr_sort)

[14 34 16 47 14 20  1 18 46 23]
[ 1 14 14 16 18 20 23 34 46 47]


- 2-й способ. Сортирует исходный массив

In [68]:
arr = np.random.randint(50, size=10)
print(arr)

arr.sort()
print(arr)

[16 21 27 22 28 30 27 37 16 40]
[16 16 21 22 27 27 28 30 37 40]


## Работа с пропущенными данными

In [69]:
arr = np.array([4, 9, -4, 3])
roots = np.sqrt(arr)
print(roots)

[2.         3.                nan 1.73205081]


C:\Users\user\AppData\Local\Temp\ipykernel_14740\616971021.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(arr)


In [73]:
print(sum(roots))

nan


In [76]:
print(np.isnan(roots))

[False False  True False]


In [78]:
print(roots[np.isnan(roots)])

[nan]


In [79]:
roots[np.isnan(roots)] = 0
print(roots)

[2.         3.         0.         1.73205081]


In [80]:
print(sum(roots))

6.732050807568877


- отличие None и np.nan.

в numpy, np.nan - это отдельный представитель класса float

In [70]:
print(type(None))
print(type(np.nan))

<class 'NoneType'>
<class 'float'>


In [71]:
print(None == None)
print(np.nan == np.nan)
print(None is None)
print(np.nan is np.nan)
print(np.nan is None)

True
False
True
True
False


In [96]:
import numpy as np
mystery = np.array(
        [ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,                 -6974.,-9212., np.nan, -17722.,  16132.,  25933.,  np.nan,             -16431.,
        29810.], 
        dtype=np.float32)


nans_index = np.isnan(mystery)
n_nan = len(mystery[np.isnan(mystery)])
mystery_new = np.array(mystery)
mystery_new[np.isnan(mystery_new)] = 0
mystery_int = np.int32(mystery)
array = np.sort(mystery)
table = array.reshape((5, 3), order='F')
print(table)
col = table[:,2]

[[-26024.  -2365.  29810.]
 [-17722.  12279.  31244.]
 [-16431.  16132.     nan]
 [ -9212.  25933.     nan]
 [ -6974.  28745.     nan]]


C:\Users\user\AppData\Local\Temp\ipykernel_14740\1660250744.py:12: RuntimeWarning: invalid value encountered in cast
  mystery_int = np.int32(mystery)
