# Модуль NumPy. Случайные числа

> Случайное число — это число, которое возникает в результате случайного процесса.

> Псевдослучайные числа — это такая последовательность чисел, которая возникает с помощью применения математических формул к какому-то исходному числу (например, текущему времени в микросекундах). Элементы, получаемые таким образом, почти не зависят друг от друга: например, при генерации следующего 0 или 1 не имеет значения, что выпало ранее — 0 или 1.

## Случайные числа в NumPy

### Генерация float

In [2]:
import numpy as np
np.random.rand() # диапазон 0 - 1 (не включительно)

0.8297197069470202

In [3]:
np.random.rand() * 100 # диапазон 0 - 100 (не включительно)

2.796034202640363

In [4]:
np.random.rand(5) # в скобке задаётся форма маccива - одномерный

array([0.50079394, 0.30170337, 0.60337243, 0.6615775 , 0.49056569])

In [5]:
np.random.rand(4, 3) # - двумерный

array([[0.61716094, 0.70503022, 0.17643578],
       [0.49439474, 0.9256029 , 0.70980089],
       [0.02003906, 0.40728097, 0.68473067],
       [0.65704364, 0.71849671, 0.83576568]])

In [6]:
np.random.rand(2, 3, 4, 10, 12, 23) # - шестимерный

array([[[[[[5.21985669e-01, 8.71411379e-01, 9.00217998e-01, ...,
            5.26401626e-01, 6.41055206e-01, 9.14858317e-01],
           [5.76283412e-01, 8.76517764e-01, 7.39691765e-01, ...,
            8.89225832e-01, 3.85753005e-02, 5.63485463e-01],
           [4.95617273e-02, 1.56451756e-01, 5.87648092e-01, ...,
            6.41986403e-01, 2.10035075e-01, 1.45161963e-01],
           ...,
           [2.33037404e-01, 6.63092563e-01, 7.35009006e-01, ...,
            5.01203523e-01, 5.03825868e-01, 5.16491054e-01],
           [1.17946062e-01, 7.25039986e-01, 2.88461278e-01, ...,
            7.93917807e-01, 3.31687387e-01, 8.83216791e-01],
           [2.68035319e-01, 6.46578485e-02, 6.51678446e-01, ...,
            8.38898217e-01, 3.27130843e-01, 7.59266600e-01]],

          [[8.46567220e-01, 2.43395693e-01, 5.36540885e-02, ...,
            7.22457753e-01, 8.99553959e-01, 8.29228977e-01],
           [8.38252796e-01, 6.30092665e-01, 7.58645017e-01, ...,
            7.74616893e-01, 3.40314

In [7]:
shape = (2, 3)
np.random.rand(shape) # rand не принимает кортажи

TypeError: 'tuple' object cannot be interpreted as an integer

In [ ]:
shape = (2, 3)
np.random.rand(*shape) # можно расспокавать но это не эстетично

array([[0.98092086, 0.05994199, 0.89054594],
       [0.5769015 , 0.74247969, 0.63018394]])

In [ ]:
shape = (5, 3)
np.random.sample(shape)

array([[0.94002982, 0.81764938, 0.33611195],
       [0.17541045, 0.37283205, 0.00568851],
       [0.25242635, 0.79566251, 0.01525497],
       [0.59884338, 0.60380454, 0.10514769],
       [0.38194344, 0.03647606, 0.89041156]])

__uniform(low=0.0, high=1.0, size=None)__
- Первые два аргумента — нижняя и верхняя границы диапазона в формате float, третий опциональный аргумент — форма массива (если не задан, возвращается одно число). Форма массива задаётся кортежем или одним числом.

In [ ]:
np.random.uniform() # 0 - 1     -одно число

0.5411305343018968

In [ ]:
np.random.uniform(5) # 0 - 5    -одно число

4.920862884198494

In [ ]:
np.random.uniform(-10, 30) # -10 - 30   -одно число

-4.3496907578086

In [ ]:
np.random.uniform(500, size=()) # 0 - 500, size=None - одно число

array(387.32519971)

In [ ]:
np.random.uniform(-1000, 500, size=())# -1000 - 500, size=None - одно число

array(-602.86549578)

In [ ]:
np.random.uniform(500, size=4) # 0 - 500 size=4 - четырёхмерный

array([167.7338141 ,  18.06864415, 390.42638689,  20.25905228])

In [ ]:
np.random.uniform(-1000, 500, size=3) # -1000 - 500 size=3 - трёхмерный

array([-346.6077479 , -350.57345832, -235.72238898])

In [ ]:
np.random.uniform(size=(2, 3)) # 0 - 1 size=(2, 3) - многомерный 2x3

array([[0.82226882, 0.72846072, 0.12565356],
       [0.89589364, 0.12486089, 0.99172865]])

In [ ]:
np.random.uniform(500, size=(2, 3)) # 0 - 1500 size=(2, 3) - многомерный 2x3

array([[439.1851834 ,  55.58021513, 166.90204694],
       [159.58687463, 305.57392309, 315.90020142]])

In [ ]:
np.random.uniform(-1000, 500, size=(2, 3)) # -1000 - 500 size=(2, 3) - многомерный 2x3

array([[ 454.24930137,   25.07067637, -140.59204191],
       [-347.74269072,  -64.11450484,  400.57878669]])

### Генерация int

randint(low, high=None, size=None, dtype=int)
> Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.

- Если указан только аргумент _low_, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.
- Если задать _low_ и _high_, числа будут генерироваться от low (включительно) до high (не включительно).
- _size_ задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.
- _dtype_ позволяет задать конкретный тип данных, который должен быть использован в массиве.

In [ ]:
np.random.randint(4, size=(2,3)) # 0-3, многомерный 2х3

array([[2, 0, 1],
       [3, 1, 0]], dtype=int32)

In [ ]:
np.random.randint(2, 5, size=(3,3)) # 2-4, многомерный 2х3

array([[3, 2, 3],
       [3, 3, 3],
       [2, 2, 2]], dtype=int32)

In [ ]:
np.random.randint(2, 5, size=3)

array([2, 3, 2], dtype=int32)

### Генерация выборок

> Случайные числа можно использовать и для работы с уже существующими данными. Иногда для проверки гипотез о данных бывает удобно перемешать значения, чтобы проверить, является ли наблюдаемая закономерность случайной.

__shuffle__

In [ ]:
arr = np.arange(6)
print(arr)
print(np.random.shuffle(arr)) #.shuffle ничего не возвращает перемешанный массив
print(arr) # модифицирует существующий массив

[0 1 2 3 4 5]
None
[1 3 5 4 2 0]


__permutation__

In [ ]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(playlist) # .permutation не изменяет исходный массив
print(shuffled) # возвращает перемешанный массив


['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']
['ACDC' 'Pink Floyd' 'Deep Purple' 'The Beatles']


>По сути, вначале создаётся массив из чисел с помощью ___arange___, а затем он перемешивается. С помощью ___permutation___ можно избежать совершения этого дополнительного действия.

In [ ]:
shuffeld_arr = np.random.permutation(10)
print(shuffeld_arr)

[5 7 8 9 2 3 6 0 1 4]


In [ ]:
np.random.permutation(10).reshape(2, 5)

array([[7, 1, 3, 8, 4],
       [6, 5, 0, 2, 9]], dtype=int32)

In [ ]:
np.random.permutation((0, 20, 50, 80 ,90))

array([90, 50, 80, 20,  0])

__choice(a, size=None, replace=True)__
- a — одномерный массив или число для генерации arange(a);
- size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
- replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).

In [ ]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choiced = np.random.choice(workers, size=2, replace=False)
print(choiced)

['John' 'Ivan']


In [ ]:
# Если попытаться получить без повторений массив большего размера, чем имеется объектов в исходном, возникнет ошибка
choiced = np.random.choice(workers, size=10, replace=False)
print(choiced)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [ ]:
choice_num = np.random.choice(20, size=10)
choice_num_1 = np.random.choice(20, size=10, replace=False)
print(choice_num)
print(choice_num_1)

[13  5  3 16 10  7  6 16 10  0]
[10  3 17  4 13  1  9  2  7 18]


In [ ]:
# Если попытаться получить c повторением массив большего размера, чем имеется объектов в исходном, ошибки не
choice = np.random.choice([1,2,3,4,5,6], size=(2,2,2))
print(choice)

[[[2 6]
  [5 6]]

 [[5 1]
  [6 6]]]


In [ ]:
table_lst = np.random.randint(1, 101, )
choice = np.random.choice(101, size=(5, 5), replace=False)
print(choice)

[[[ 29  37  53  88  13]
  [ 80  91  64  21  86]
  [ 94  69  57  93  41]
  [ 54   6  51  78  24]
  [ 44  58  82  79  99]]

 [[ 35  26 100  65  74]
  [ 70  11  43  81   1]
  [ 18  75  23  38  73]
  [ 30  71  60  42   9]
  [ 45  47  40  85   7]]

 [[ 98   3  10   0  34]
  [ 15   5  66  19  36]
  [ 89  27  12  31  59]
  [ 97  76  16   4  62]
  [ 20  96  72  46  87]]]


## Seed генератора псевдослучайных чисел

>Как уже было сказано ранее, NumPy генерирует не истинные случайные числа (такие числа получаются в результате случайных процессов), а псевдослучайные, которые получаются с помощью особых преобразований какого-либо исходного числа. Обычно компьютер берёт это число автоматически, например, из текущего времени в микросекундах (на самом деле используются другие ещё менее предсказуемые числа). Такое число называют seed (от англ. — «зерно»).

>>Самостоятельно задать seed в NumPy можно с помощью функции __np.random.seed(<np.uint32>)__. Число в скобках должно быть в пределах от ___0 до 2**32 - 1 (=4294967295)___.

In [ ]:
np.random.seed(23)
print(np.random.randint(10, size=(2,3)))
print(np.random.rand(2, 3))
print(np.random.sample((2,3))),
print(np.random.uniform(0, 20, size=(2,3)))
print(np.random.permutation(10).reshape(2, 5))

NameError: name 'np' is not defined

In [ ]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

[8 8 3]
[7 7 0]
[4 2 5]


In [19]:
import numpy as np
def get_unique_loto(num):
    sample = np.arange(1, 101)
    res = list()
    for i in range(num):
        res.append(np.random.choice(sample, replace=False, size=(5, 5)))
    res = np.array(res)
    return res

print(get_unique_loto(10))

[[[ 46  30  40  35  38]
  [ 62  83  77  42  25]
  [ 23  37  64   4  53]
  [ 69  56  98   2  71]
  [  9   8  31   7  49]]

 [[ 55  63  75  86  45]
  [ 88  90  54  79  66]
  [ 29  39  64  69  30]
  [ 83  21  58   8  10]
  [ 25  68  97  41  14]]

 [[ 58  12  65  75  80]
  [ 92  84   5  73   2]
  [ 26   6  37  45  30]
  [ 68  72  14  11  17]
  [ 91 100  94  78  50]]

 [[ 47  29  87  85   8]
  [ 60  27   4  16  83]
  [ 67  81  62  33  20]
  [ 49  50  32  74  56]
  [ 99   2  61  40   9]]

 [[ 39  57  71  79  19]
  [ 21  93  99  63  49]
  [ 36  70  56  13  28]
  [ 85  94  76  58  25]
  [ 89  75   7  24  44]]

 [[ 80  89  45   1  16]
  [ 32  47  95  21  96]
  [ 93  25  31  33  98]
  [ 24  28  44  36  69]
  [ 59  46  75  76  88]]

 [[ 48  75  23  96   7]
  [ 34  74  19  62  30]
  [ 76  90  60  41  77]
  [ 83  25  95  14  98]
  [ 81  33   6  71  42]]

 [[ 53  86  79  16  33]
  [ 63  26  81  72  48]
  [ 41  29   1  91   9]
  [ 98  95  17  24  94]
  [ 27  90  12  50  34]]

 [[ 99  27  95  11  62]
