# Модуль NumPy. Массивы

МАССИВ — это структура данных, в которой:
1. Элементы хранятся в указанном порядке.
2. Каждый элемент можно получить по индексу за одинаковое время.
3. Все элементы приведены к одному и тому же типу данных.
4. Максимальное число элементов и объём выделенной памяти заданы заранее (программистом и/или компьютером)

__Размерностью массива__ называют то число индексов, которое необходимо для однозначного получения элемента из массива.
- соответственно, чтобы найти элемент в массиве размерности 1 (строка из чисел) достаточно одного индекса.
- В двумерном массиве (таблице из чисел) потребуется уже два индекса: номер строки и номер столбца.
- Для трёхмерного массива (например, контейнеры на судне расположены по длине, ширине и высоте судна) потребуется уже три индекса.
>Максимальная размерность массива программно не ограничена, но с добавлением каждой размерности в несколько раз увеличивается объём требуемой для его хранения памяти. Поэтому в какой-то момент места для массива большой размерности может не хватить, однако фактическая максимальная размерность зависит от возможностей компьютера.

__Форма (структура) массива__ — это информация о количестве размерностей массива и протяжённости массива по каждой из размерностей. Например, можно задать двумерный массив размера 3x5 — у этой таблицы две размерности: 3 строки и 5 столбцов.

## Массивы в Numpy

### 1. Создание массива из списка

In [2]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr 

array([ 1,  5,  2,  9, 10])

In [3]:
print(arr) # пример вывода без print (выше) и с print

[ 1  5  2  9 10]


In [4]:
print(type(arr))
# Название ndarray — это сокращение от n-dimensional array, n-мерный массив.

<class 'numpy.ndarray'>


In [5]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [6]:
print(nd_arr) # пример вывода без print (выше) и с print

[[12 45 78]
 [34 56 13]
 [12 98 76]]


## 2. Типы данных в массиве

In [7]:
arr = np.array([1,5,2,9,10])
arr.dtype
# NumPy автоматически определил наш набор чисел как числа типа int64.

dtype('int64')

In [8]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [9]:
print(arr) # пример вывода без print (выше) и с print

[ 1  5  2  9 10]


In [10]:
arr[2] = 2000 % -128 # -128 - это мин знач для np.int8
arr

array([  1,   5, -48,   9,  10], dtype=int8)

In [11]:
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [12]:
# Строку, которую можно преобразовать в число, можно сразу положить в массив. Она будет приведена к нужному типу автоматически:
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [13]:
arr[2] = 'test'
arr

ValueError: invalid literal for int() with base 10: 'test'

In [ ]:
arr = np.float64(arr)
arr

array([ 1.,  5., 12.,  9., 10.])

>>При преобразовании типов данных в массиве не забывайте о том, что часть чисел может потерять смысл, если менять тип данных с более ёмкого на менее ёмкий:

In [ ]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr

array([12321, -1234,  3435,  -214,   100], dtype=int32)

In [ ]:
arr = np.uint8(arr)
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

## 3. Свойства NumPy-массивов

In [ ]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

1. Размерность массива

In [ ]:
arr.ndim
# одномерный 

1

In [ ]:
nd_arr.ndim
# двумерный

2

2. Общее число (кол-во) элементолв в массиве

In [ ]:
arr.size

5

In [ ]:
nd_arr.size

9

3. Форма или структура массива

In [ ]:
arr.shape

(5,)

In [ ]:
nd_arr.shape

(3, 3)

4. Размер ("вес") каждого элемента в массиве (сколько байт)

In [ ]:
arr.itemsize

1

In [ ]:
nd_arr.itemsize

2

>> Что б найти размер (вес) всех элементов массива надо вес каждогомассива умножить на общее число массивов ххх.itemsize * ххх.size

## 4. Заполнение новых массивов

→ Не всегда значения, которые будут храниться в массиве, уже доступны, а иметь для них массив уже хочется.

- нулевой массив

In [ ]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [ ]:
zeros_2d = np.zeros((5, 3), dtype=np.int8)
zeros_2d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [ ]:
zeros_3d = np.zeros((5, 4, 3), dtype=np.float32)
zeros_3d.shape

(5, 4, 3)

In [ ]:
zeros_3d = np.zeros((5, 4, 3), dtype=np.float32)
zeros_3d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

- удобные функции для создания одномерных массивов

>в отличие от __range__, в функции __arange__ все параметры могут быть float 

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(2.5, 5)

array([2.5, 3.5, 4.5])

In [ ]:
np.arange(2.5, 5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
np.arange(2.5, 5.5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

>> Операции с плавающей точкой не всегда бывают предсказуемыми из-за особенностей хранения таких чисел в памяти компьютера. Поэтому в __arange__  не рекомендуется использовать float

Для работы с дробными параметрами start, stop и step лучше использовать функцию ___linspace___ (англ. linear space — линейное пространство). Она тоже возвращает одномерный массив из чисел, расположенных на равном удалении друг от друга между началом и концом диапазона, но обладает немного другим поведением и сигнатурой:

__np.linspace (start, stop, num=50, endpoint=True, retstep=False, dtype=None)__

- start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
- num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
- endpoint — включён или исключён конец диапазона (по умолчанию включён, т.е. включает конец диапазона);
- retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
- dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).


In [ ]:
arr = np.linspace(1, 2, 10)
arr
# Массив из десяти чисел между 1 и 2, включая 2

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
arr = np.linspace(1, 2 , 10, endpoint=False)
arr
# Создадим массив из десяти чисел между 1 и 2, НЕ включая 2

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(arr)
print(step)
# какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
0.1111111111111111


In [ ]:
arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(arr)
print(step)
# какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 НЕ включалось

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
0.1


> Функцию linspace очень удобно использовать при построении графиков различных функций, поскольку она позволяет получить равномерный массив чисел, к которому можно применить исследуемую функцию и показать результат на графике.

In [ ]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(arr, end='\n\n')
print(step)

[-6.   -5.55 -5.1  -4.65 -4.2  -3.75 -3.3  -2.85 -2.4  -1.95 -1.5  -1.05
 -0.6  -0.15  0.3   0.75  1.2   1.65  2.1   2.55  3.    3.45  3.9   4.35
  4.8   5.25  5.7   6.15  6.6   7.05  7.5   7.95  8.4   8.85  9.3   9.75
 10.2  10.65 11.1  11.55 12.   12.45 12.9  13.35 13.8  14.25 14.7  15.15
 15.6  16.05 16.5  16.95 17.4  17.85 18.3  18.75 19.2  19.65 20.1  20.55]

0.45
