# Градиент и антиградиент

### Вычисление градиента для числовых векторов в Python

In [1]:
import numpy as np
f = np.array([3, 7, 14, 23, 36 ,47])
np.gradient(f)

array([ 4. ,  5.5,  8. , 11. , 12. , 11. ])

In [2]:
'''
Если специально не определять аргумент varargs, то его значение равно 1, так что на границах вектора мы 
получаем обычную разность для соседних элементов массива:
'''
print(f[1] - f[0], f[-1] - f[-2])

'''
А вот внутри вектора для каждого элемента мы считаем разность его соседних значений, но уже поделённую на 2:
'''
print((f[2] - f[0])/2) # 5.5
print((f[3] - f[1])/2) # 8.0
print((f[4] - f[2])/2) # 11.0
print((f[5] - f[3])/2) # 12.0

4 11
5.5
8.0
11.0
12.0


In [3]:
'''
Шаг можно варьировать. При его изменении вычисления реализуются так же, но деление происходит на величину 
обычного шага у края и удвоенную величину шага для элементов внутри вектора
'''
step = 2
np.gradient(f, step)

array([2.  , 2.75, 4.  , 5.5 , 6.  , 5.5 ])

In [4]:
# пример как np.gradient() рачитывает внутривектора (не на границах)
for i in range(1, len(f) - 1):
        print((f[i + 1] - f[i - 1])/(2*step))

2.75
4.0
5.5
6.0


In [5]:
from sympy import symbols, diff, solve
a, b = symbols('a, b', real=True)
f = (5 - a - 2*b)**2
print(diff(f,a))
print(diff(f,b))


2*a + 4*b - 10
4*a + 8*b - 20


In [6]:

w0, w1 = symbols('w0, w1', real=True)
f = (2.1 - w0 - w1)**2 + (2.9 - w0 - 3*w1)**2 + (4.1 - w0 -5*w1)**2
print(diff(f, w0))
print(diff(f, w1))

solutions = solve([diff(f, w0), diff(f, w1)], w0, w1)
print(solutions)

6*w0 + 18*w1 - 18.2
18*w0 + 70*w1 - 62.6
{w0: 1.53333333333333, w1: 0.500000000000000}


In [7]:
f = np.array([8, 2, 8, 3, 5, 6, 5, 15])
np.gradient(f, 7)

array([-0.85714286,  0.        ,  0.07142857, -0.21428571,  0.21428571,
        0.        ,  0.64285714,  1.42857143])