# Домашнее задание

Математический анализ
69 баллов

**Задача 1** (14 баллов)

Найдите экстремумы функции:

$$
f(x, y, z)=2 x^3+2 x y+2 x z+y^2+z^2+2 y-8 .
$$

Распишите подробное решение.

In [52]:
from sympy import symbols, diff, solve, Eq, Matrix
import numpy as np
# объявляем все необходимые переменные и функцию
x, y, z = symbols('x, y, z', real=True)
f = 2*x**3 + 2*x*y + 2*x*z + y**2 + z**2 + 2*y - 8

# вычиляем все частные поизводные
x_diff = diff(f, x)
y_diff = diff(f, y)
z_diff = diff(f, z)
print(f'Система уравнений (первые частные производные):\n{x_diff} = 0\n{y_diff} = 0\n{z_diff} = 0\n')

# решаем систему уравений, вычисляем стационарные точки
stat_point = solve((x_diff, y_diff, z_diff), x, y ,z, dict=True)
print(f'Стационарные точки {stat_point}\n')

# Вычисляем все частные произврдные 2-ого порядка
# 1-й метод
hes_matrix = Matrix(([diff(f, x, x), diff(f, x, y), diff(f, x, z)], 
                    [diff(f, y, x), diff(f, y, y), diff(f, y, z)],
                    [diff(f, z, x), diff(f, z, y), diff(f, z, z)]))
print(f'Матрица Гесса (вторые частные прогизводные):\n{np.array(hes_matrix)}\n')


# подставляем стационарные точки в матрицу Гесса и вычислим собственные числа
print(f'Подставим стационарные точки в матрицу Гесса и вычислим собственные значения:')
for i_point in stat_point:
    hes_matr_num = hes_matrix.subs({x:i_point[x], y:i_point[y], z:i_point[z]})
    eigs = [float(i_eig) for i_eig in hes_matr_num.eigenvals().keys()]
    
    print(f'\nСтационарные точки:\n{i_point}\nМатрица Гессе:\n{np.array(hes_matr_num)}')
    print(f'Cобственные значения матрицы Гессе:\n{eigs}')
    
    if all(i>0 for i in eigs):
        print(f'ВЫВОД: точки {i_point} - точка МИНИМУМА')
    elif all(i<0 for i in eigs):
        print(f'ВЫВОД: точки {i_point} - точка МАКСИМУМА')
    else:
        print(f'ВЫВОД: точки {i_point} - СЕДЛОВАЯ точка')

Система уравнений (первые частные производные):
6*x**2 + 2*y + 2*z = 0
2*x + 2*y + 2 = 0
2*x + 2*z = 0

Стационарные точки [{x: -1/3, y: -2/3, z: 1/3}, {x: 1, y: -2, z: -1}]

Матрица Гесса (вторые частные прогизводные):
[[12*x 2 2]
 [2 2 0]
 [2 0 2]]

Подставим стационарные точки в матрицу Гесса и вычислим собственные значения:

Стационарные точки:
{x: -1/3, y: -2/3, z: 1/3}
Матрица Гессе:
[[-4 2 2]
 [2 2 0]
 [2 0 2]]
Cобственные значения матрицы Гессе:
[2.0, -5.123105625617661, 3.1231056256176606]
ВЫВОД: точки {x: -1/3, y: -2/3, z: 1/3} - СЕДЛОВАЯ точка

Стационарные точки:
{x: 1, y: -2, z: -1}
Матрица Гессе:
[[12 2 2]
 [2 2 0]
 [2 0 2]]
Cобственные значения матрицы Гессе:
[2.0, 1.2554373534619714, 12.744562646538029]
ВЫВОД: точки {x: 1, y: -2, z: -1} - точка МИНИМУМА


___

**Задача 2** (25 баллов)

Найдите условные экстремумы функции:

$$
f(x, y)=4 x+8 y, y^2-2 x y+5=0
$$

Вычислите результат самостоятельно (вручную) и с помощью Python. Сравните результаты.

__1) Вычисение резульатат вручную__

1. Функция Лагранжа  
$$
L(x, y, \lambda) = 4x + 8y + \lambda(y^2 - 2xy + 5)
$$
2. Вычисляе все частные производные по $x, y, \lambda$  
$$
L'(x) = 4 - 2\lambda
$$
$$
L'(y) = 8 + 2\lambda y - 2\lambda x
$$
$$
L'(\lambda) = y^2 - 2xy + 5
$$
3. Все частные производные приравниваем к "0" и решаем систему уравнений  
$
\begin{cases}
4 - 2\lambda y = 0\\
8 + 2\lambda y - 2\lambda x = 0\\ 
y^2 - 2xy + 5 = 0
\end{cases}  
$\
(2)+(1), из (1) находим $y$, из (2) находим $x$, $y$ и $x$ подставляем в (3)-решаем и находим $\lambda$\
$
\begin{cases}
4 - 2\lambda y = 0\\
8 - 2\lambda x = 0\\ 
y^2 - 2xy + 5 = 0
\end{cases}   
$
$
\begin{cases}
y = \frac{2}{\lambda}\\
x = \frac{6}{\lambda}\\ 
\frac{4}{\lambda^2} - 2 \frac{2}{\lambda} \frac{6}{\lambda} = 5
\end{cases}   
$
$
\begin{cases}
y = \frac{2}{\lambda}\\
x = \frac{6}{\lambda}\\ 
\frac{4}{\lambda^2} - \frac{24}{\lambda^2} = 5
\end{cases}   
$
$
\begin{cases}
y = \frac{2}{\lambda}\\
x = \frac{6}{\lambda}\\ 
5\lambda^2 = 20
\end{cases}   
$
$
\begin{cases}
y = \frac{2}{\lambda}\\
x = \frac{6}{\lambda}\\ 
\lambda = \pm20
\end{cases}   
$
$
\begin{cases}
y = \pm 1\\
x = \pm 2\\ 
\lambda = \pm 4
\end{cases}   
$  

4. Подставляем полученные $x$ и $y$ в целевую функцию $f(x, y) = 4x + 8y$
$$
f(3,1) = 4*3+8*1=20
$$
$$
f(-3,-1) = 4*(-3)+8*(-1)=-20
$$
> __ВЫВОД__:  
в точке (3, 1) - целевая функция достигает МАКСИМУМА  
в точке (-3, -1) - целевая функция достигает МИНИМУМА


__2) Вычисление результата с помощью Python__

In [ ]:
# объявляем все необходимые переменные, целевую функцию и условие 
x, y, l = symbols('x, y, l', real = True)
f_maim = 4*x + 8*y
f_cond = y**2 - 2*x*y + 5
f_lagran = f_maim + l * f_cond

# вычиляем все частные поизводные
x_diff = diff(f_lagran, x)
y_diff = diff(f_lagran, y)
l_diff = diff(f_lagran, l)
print(f'Система уравнений (первые частные производные):\n{x_diff} = 0\n{y_diff} = 0\n{l_diff} = 0\n')

# решаем систему уравений, вычисляем стационарные точки
stat_pnt = solve([x_diff, y_diff, l_diff], x, y, l, dict=True)
print(f'Стационарные точки {stat_pnt}\n')

# подставим собственные числа в целевую функцию и расчитаем значение функции
for i_pnt in stat_pnt:
    f_main_result = f_maim.subs({x: i_pnt[x], y: i_pnt[y]})
    print(f'f(x,y) = {f_main_result}')
    if f_main_result < 0:
        print(f'в точке x:{i_pnt[x]}, y:{i_pnt[y]} - целефая функция достигает точки МИНИМУМА\n')
    else:
        print(f'точке x:{i_pnt[x]}, y:{i_pnt[y]} - целефая функция достигает точки МАКСИМУМА\n')

Система уравнений (первые частные производные):
-2*l*y + 4 = 0
l*(-2*x + 2*y) + 8 = 0
-2*x*y + y**2 + 5 = 0

Стационарные точки [{l: -2, x: -3, y: -1}, {l: 2, x: 3, y: 1}]

f(x,y) = -20
точки x:-3, y:-1 - целефая функция достигает точки МИНИМУМА

f(x,y) = 20
точки x:3, y:1 - целефая функция достигает точки МАКСИМУМА



___

**Задача 3** (30 баллов)

Вам предложены данные с информацией о успеваемости студентов:

Независимые переменные:
* Hours Studied: Общее количество часов, потраченных на учебу каждым студентом.
* Previous Scores: Баллы, полученные студентами на предыдущих экзаменах.
* Sleep Hours: Среднее количество часов сна студента в сутки.
* Sample Question Papers Practiced: Количество пробных экзаменационных работ, с которыми студент занимался.
  
Целевая переменная:
* Performance Index: Показатель общей успеваемости каждого студента. Индекс успеваемости отражает академическую успеваемость студента и округляется до ближайшего целого числа. Индекс варьируется от 10 до 100, при этом более высокие значения свидетельствуют о более высокой успеваемости.

**Решите задачу линейной регрессии, реализовав градиентный спуск самостоятельно, не используя готовое решение из какой-либо библиотеки.**

In [134]:
import numpy as np
import pandas as pd

df = pd.read_csv('HW_1_Task_3_data.txt')

In [135]:
df.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [146]:
X = df[['Hours Studied', 'Previous Scores', 'Sleep Hours', 'Sample Question Papers Practiced']]
y = df['Performance Index']

mu = X.mean()
sigma = X.std()
X = (X - mu) / sigma

n = len(y)
X = np.append(np.ones((n,1)), X.values.reshape(n,4), axis = 1)
y = df['Performance Index'].values.reshape(n,1)
par = np.zeros((5,1))

print(X)

[[ 1.          0.77514895  1.70409044  1.45613179 -1.24969145]
 [ 1.         -0.38346141  0.72387648 -1.49221962 -0.9009371 ]
 [ 1.          1.16135241 -1.06357251  0.27679123 -0.9009371 ]
 ...
 [ 1.          0.3889455   0.78153612  0.86646151  0.14532594]
 [ 1.          1.54755586  1.58877115  0.27679123 -1.5984458 ]
 [ 1.          0.77514895  0.26259932  0.86646151 -1.24969145]]


In [147]:
def cost_function(X, y , par):
    y_pred = np.dot(X, par)
    error = (y_pred - y)**2
    cost = 1/(n)*np.sum(error)
    return cost

def grad_d(X, y, par, alpha, iterations):
    costs = []
    for i in range(iterations):
        y_pred = np.dot(X, par)
        der = np.dot (X.transpose(), (y_pred - y))/ n
        par -= alpha * der
        costs.append(cost_function(X, y, par))
    return par, costs

In [149]:
par, costs_opt = grad_d(X, y, par, 0.5, 5000)

In [150]:
par

array([[55.2248    ],
       [ 7.38840936],
       [17.66544939],
       [ 0.80779547],
       [ 0.5597014 ]])

In [151]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)
print(model.coef_)
print(model.intercept_)

[[ 0.          7.38840936 17.66544939  0.80779547  0.5597014 ]]
[55.2248]
