# Модуль NumPy. Операции с векторами

> В программировании вектором называют одномерный проиндексированный набор данных, другими словами — одномерный массив.

## Векторы в NumPy и арифметика

In [1]:
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
print(vec1 + vec2) # сложение вектора массива

[14.  10.  10.6 15.5]


In [2]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2 # сложение списков

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [3]:
[x + y for x, y in zip(list1, list2)]  # сложить 2 списка поэлементно 

[14, 10, 10.6, 15.5]

>> Для совершения арифметических операций с векторами они должны быть одинаковой длины.

In [4]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [5]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6])
vec1 * vec2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
vec = np.arange(5)
print(vec * 10)
vec ** 2

[ 0 10 20 30 40]


array([ 0,  1,  4,  9, 16])

In [ ]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1 > vec2 

array([False, False,  True, False])

In [ ]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

## Продвинутые операции с векторами

1. __Длина__ вектора, то есть расстояние между его началом и концом, [в евклидовом пространстве] вычисляется как квадратный корень из суммы квадратов всех его координат. Для вектора из n чисел x1, x2 … xn верна формула:

$$
\ lenght \ = \sqrt{a_1^2 + a_2^2 + \dots + a_n^2}
$$

In [ ]:
vec  = np.array([3, 4])

In [ ]:
vec_len = np.sqrt(np.sum(vec ** 2)) # из фурмулы
vec_len

np.float64(5.0)

In [ ]:
vec_len = np.linalg.norm(vec) # из модуля numpy и подмодуля linalg. norm - длина вектора
vec_len

np.float64(5.0)

2. __Расстояние__ между двумя векторами, то есть ___расстояние между их концами___, [в евклидовом пространстве] вычисляется как квадратный корень из суммы квадратов разностей соответствующих координат. Звучит сложно, поэтому лучше посмотрите на формулу (считаем расстояние между векторами X и Y):

$$
\ distance \ = \sqrt{(a_1 - b_1)^2 + (a_2 - b_2)^2 + \dots + (a_n - b_n)^2}
$$

> По сути, расстояние между векторами — это длина такого вектора, который является разностью этих векторов. В самом деле, при вычитании двух векторов вычитаются их соответствующие координаты.

In [ ]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
dist = np.sqrt(np.sum((vec1 - vec2) ** 2)) # из формулы
dist

np.float64(12.206555615733702)

In [ ]:
dist = np.linalg.norm(vec1 - vec2) # из модуля numpy и подмодуля linalg
dist

np.float64(27.248853186877426)

3. __Скалярным__ произведением двух векторов называют сумму произведений их соответствующих координат. Вот формула для скалярного произведения векторов X и Y из  координат:

$$
\ X * Y \ =  x_1 * y_1 + x_2 * y_2 + \dots + x_n *y_n

In [ ]:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_dot = np.sum(vec1 * vec2) # из фомулы
scalar_dot

np.float64(250.0)

In [ ]:
scalar_dot = np.dot(vec1, vec2)
scalar_dot

np.float64(250.0)

> Если скалярное произвдение = 0, => векторы перпендикулярны (отогональный друг к другу)

In [ ]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

np.int64(0)

___

> __Сонаправленные векторы__ если они коллинеарны и их направления совпадают 
>> ___сумма длин сонаправленных векторов должна быть равной длине суммы двух векторов___

___

## Базовые статистические функции для векторов

In [ ]:
vec = np.array([2,7,18,28,18,1,8,4])

- min

In [ ]:
vec.min()

np.int64(1)

In [ ]:
np.min(vec)

np.int64(1)

- max

In [ ]:
vec.max()

np.int64(28)

In [ ]:
np.max(vec)

np.int64(28)

- mean (средняя)

In [ ]:
vec.mean()

np.float64(10.75)

In [ ]:
np.mean(vec)

np.float64(10.75)